<?php

return [

    'name' => env('APP_NAME', 'webAS'),

    'env' => env('APP_ENV', 'production'),

    'debug' => (bool) env('APP_DEBUG', false),

    'url' => env('APP_URL', 'http://localhost'),

    'timezone' => 'Europe/Istanbul',

    'locale' => env('APP_LOCALE', 'tr'),

    'fallback_locale' => 'tr',

    'faker_locale' => 'tr_TR',

    // Read from an .env value generated by `php artisan key:generate`
    // (see backend/README.md) — required for any encrypted cookie/session
    // Laravel itself creates; NOT used for the auth_token JWT, which is
    // signed with config('webas.jwt_secret') instead (see AdminJwt).
    'cipher' => 'AES-256-CBC',

    'key' => env('APP_KEY'),

    'previous_keys' => [
        ...array_filter(
            explode(',', env('APP_PREVIOUS_KEYS', ''))
        ),
    ],

    'maintenance' => [
        'driver' => env('APP_MAINTENANCE_DRIVER', 'file'),
        'store' => env('APP_MAINTENANCE_STORE', 'database'),
    ],

];
